### PR TITLE
html5 parser and some fix

### PR DESCRIPTION
**Pull request by vthriller**

### CODE REVIEW

**Comment by drzraf** [comment]
This parser is the only one which handle fragments and treat them as UTF-8.
But how are selector expected to work with this parser?
Every tag is namespaced by "html", eg:
``<html:div id="blah">``
Selecting such an elements is impossible because "html:div" is a pseudo-class selector syntax.
Example/tests would be useful.

**Comment by drzraf** [comment]
and @gawel  for ping

**Comment by gawel** [comment]
Try using https://pythonhosted.org/pyquery/api.html?highlight=namespace#pyquery.pyquery.PyQuery.remove_namespaces

**Comment by drzraf** [comment]
that works. Thank you!

I'd have removed my workaroud but... I found that html5 parser is 40%
slower than lxml.html.HTMLParser.

But I keep in mind this remove_namespaces() advise.

**Pull request merged**
