### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by doyousketch2**
http://stackoverflow.com/questions/21489720/installing-pyquery-via-pip

### CODE REVIEW

**Comment by gawel** [comment]
PyQuery is multi-platform
May be linking to http://lxml.de/installation.html instead is a better idea

**Comment by doyousketch2** [comment]
When you install pyquery with pip, it automatically installs lxml for you.

If they get pip on their system, they should be fine.

I'll update it so it shows pip installs for win and mac.

**Comment by gawel** [comment]
Yes I know. But installation problems always came from lxml. So why having a complex install section when you just need to says "if you experiment problems see this link"

The linux section still wrong. Not all linux distro use apt. And why not using apt-get install python-pyquery when your installing python-lxml on debian based distro?

You don't need the -dev packages if you're installing python-lxml. Those are required to pip install lxml.

Really, I'm not sure this is a good idea.

**Comment by gawel** [comment]
Dont need this since lxml provides wheels

**Pull request closed without merging**
