### PR TITLE
Fix some rst in CHANGES.rst

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by gawel** [comment]
You're sure that this is your last changes ? You have to understand that I can make a release each day. pyquery is followed/packaged by some linux distros and I don't want to bother them with 365 releases per year. If you really need a up to date version you can always use ```pip install -e git+giturl```

**Comment by asottile** [comment]
Sorry about the many changes.  I'm currently hacking through a [very large](https://engineeringblog.yelp.com/2016/08/undebt-how-we-refactored-3-million-lines-of-code.html) codebase and hitting lots of edgecases.  I *think* this should be the last of them but you can hold off on releasing until next week if it's too much work :)

**Comment by gawel** [comment]
No problem. Your contributions are very welcome.

Releasing is not hard work. I'm using the fullrelease script of zest.releaser. http://zestreleaser.readthedocs.io/en/latest/ This big red button do everything for you: bump version in setup.py & changelog / git tag / sdist / upload to pypi. This take at least 5s :)

I just want to avoid unnecessary release. Try to use the pip -e trick if possible. You can freeze at a specific changeset if you want a "stable" base. pip -e git+giturl@changeset as I remember

**Comment by asottile** [comment]
yep that's what I'm already doing :)

we of course have release processes which prevent us from going to production like that but for development it works :)

**Pull request merged**
