### PR TITLE
text() output compatible with selenium .text property #99

### PR DESCRIPTION
**Pull request by neumond**
I'm not sure how to organize tests. They consist of two parts:
- testing selenium output to ensure correctness of TextExtractionMixin
- testing our code with same TextExtractionMixin

I don't know whether Travis supports selenium, so I put my tests separately.

```bash
python -m unittest seleniumtests.offline
python -m unittest seleniumtests.browser
```

Added same lines to tox config, but `browser` test hangs.
You can change selenium driver in `browser.py:71`. Recent Firefox hangs, but Chrome worked for me. Under tox both hang, probably due to lack of some envvars, like current X display.

### CODE REVIEW

**Comment by neumond** [comment]
Obviously it requires backporting to 2.7 as well.

**Comment by neumond** [comment]
I've spent an hour trying to ignore browser.py in nosetests. Still out of luck..

**Comment by gawel** [comment]
I've fixed the .clear() problem but it seems that some chars are striped with 2.7. Any idea why ? I thought of a str vs unicode problem but it seems not.

**Comment by neumond** [comment]
Yea, it was good old str vs unicode problem, but with regex line.

**Comment by gawel** [comment]
Great, thanks. I still need to dig into those selenium tests. But it seems good to merge.

**Comment by neumond** [comment]
Technically they are the same unittests running twice: against selenium and against text() code. That part with text() code could be merged into primary test suite: it does not require selenium. Selenium part just ensures we have consistent output and can be used to track changes in selenium itself. AFAIK travis is able to run headless firefox, so this can be automated.

**Comment by gawel** [comment]
FYI, I've managed to get your tests running under travis with py36. See https://travis-ci.org/gawel/pyquery/jobs/327821032

Also they are now all located in tests/

Thanks again. This is really valuable!

**Pull request merged**
